In [2]:
import pandas as pd
import requests
pd.set_option('display.max_columns',None) # To see all columns in a wide DataFrame
import time
import numpy as np

In [59]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2012-13&SeasonType=Regular%20Season&StatCategory=PTS'

In [62]:
#go to nba stats.com >> right click inspect >> network >> check Fetch/XHR >> leagueleaders >> preview >> general look for request URL
r = requests.get(url=test_url).json()

In [63]:
#To look for column headers
table_headers = r['resultSet']['headers']

In [64]:
r['resultSet']['rowSet'][0]

[201142,
 1,
 'Kevin Durant',
 1610612760,
 'OKC',
 81,
 3119,
 731,
 1433,
 0.51,
 139,
 334,
 0.416,
 679,
 750,
 0.905,
 46,
 594,
 640,
 374,
 116,
 105,
 280,
 143,
 2280,
 2462,
 1.34,
 0.41]

In [65]:
pd.DataFrame(r['resultSet']['rowSet'],columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,203130,463,Darius Johnson-Odom,1610612747,LAL,4,6,0,4,0.000,0,1,0.000,0,0,0.000,1,3,4,1,0,0,0,0,0,1,0.00,0.00
464,2545,463,Darko Milicic,1610612738,BOS,1,5,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,2,1,0,-2,0.00,0.00
465,202458,463,Justin Dentmon,1610612742,DAL,2,4,0,2,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
466,2679,463,Matt Carroll,1610612766,CHA,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,1,0,1,0.00,0.00
467,200780,463,Solomon Jones,1610612752,NYK,2,26,0,1,0.000,0,0,0.000,0,0,0.000,1,2,3,0,0,1,3,3,0,0,0.00,0.00

In [66]:
#temp_df1 - existing columns
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'],columns = table_headers)
#temp_df2 to add year and season type column
temp_df2 = pd.DataFrame({'Year':['2022-23' for i in range(len(temp_df1))],
                         'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
#temp_df3 to concat temp_df1 and temp_df2
temp_df3 = pd.concat([temp_df2,temp_df1],axis=1)
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2022-23,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,2022-23,Regular%20Season,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2022-23,Regular%20Season,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,2022-23,Regular%20Season,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2022-23,Regular%20Season,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,2022-23,Regular%20Season,203130,463,Darius Johnson-Odom,1610612747,LAL,4,6,0,4,0.000,0,1,0.000,0,0,0.000,1,3,4,1,0,0,0,0,0,1,0.00,0.00
464,2022-23,Regular%20Season,2545,463,Darko Milicic,1610612738,BOS,1,5,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,2,1,0,-2,0.00,0.00
465,2022-23,Regular%20Season,202458,463,Justin Dentmon,1610612742,DAL,2,4,0,2,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
466,2022-23,Regular%20Season,2679,463,Matt Carroll,1610612766,CHA,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,1,0,1,0.00,0.00
467,2022-23,Regular%20Season,200780,463,Solomon Jones,1610612752,NYK,2,26,0,1,0.000,0,0,0.000,0,0,0.000,1,2,3,0,0,1,3,3,0,0,0.00,0.00

In [67]:
del temp_df1, temp_df2, temp_df3

## Code to scrap datasets from past few years including regular seasons & playoff stats

In [68]:
df_cols = ['Year','Season_type'] + table_headers

In [69]:
pd.DataFrame(columns=df_cols)

Empty DataFrame
Columns: [Year, Season_type, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [70]:
# inspect >> network >> Fetch/XHR >> Headers >> Request Headers >> Copy
headers = {
    'Accept':' */*'
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Origin': 'https://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'sec-ch-ua': '"Not_A Brand";v="99", "Google Chrome";v="109", "Chromium";v="109"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': "Windows",
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
}'

SyntaxError: invalid syntax (1563720149.py, line 4)

In [71]:
df = pd.DataFrame(columns=df_cols)
season_types = ['Regular%20Season','Playoffs']
years = ['2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21','2021-22','2022-23']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url = api_url).json()
        #temp_df1 - existing columns
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'],columns = table_headers)
        #temp_df2 to add year and season type column
        temp_df2 = pd.DataFrame({'Year':[y for i in range(len(temp_df1))],
                                 'Season_type':[s for i in range(len(temp_df1))]})
        #temp_df3 to concat temp_df1 and temp_df2
        temp_df3 = pd.concat([temp_df2,temp_df1],axis=1)
        df = pd.concat([df,temp_df3],axis=0)
        print(f'Finished scraping data for the {y} {s}.')
        lag = np.random.uniform(low=5,high=40)
        print(f'...waiting {round(lag,1)} seconds')
        time.sleep(lag)

print(f'Process completed! Total run time: {round((time.time() - begin_loop)/60,2)}')
#save files 
df.to_excel('nba_player_data.xlsx',index = False)

Finished scraping data for the 2012-13 Regular%20Season.
...waiting 34.2 seconds
Finished scraping data for the 2012-13 Playoffs.
...waiting 24.6 seconds
Finished scraping data for the 2013-14 Regular%20Season.
...waiting 8.3 seconds
Finished scraping data for the 2013-14 Playoffs.
...waiting 6.1 seconds
Finished scraping data for the 2014-15 Regular%20Season.
...waiting 23.5 seconds
Finished scraping data for the 2014-15 Playoffs.
...waiting 38.8 seconds
Finished scraping data for the 2015-16 Regular%20Season.
...waiting 31.2 seconds
Finished scraping data for the 2015-16 Playoffs.
...waiting 8.4 seconds
Finished scraping data for the 2016-17 Regular%20Season.
...waiting 8.4 seconds
Finished scraping data for the 2016-17 Playoffs.
...waiting 35.7 seconds
Finished scraping data for the 2017-18 Regular%20Season.
...waiting 34.9 seconds
Finished scraping data for the 2017-18 Playoffs.
...waiting 17.1 seconds
Finished scraping data for the 2018-19 Regular%20Season.
...waiting 23.8 seconds
Finished scraping data for the 2018-19 Playoffs.
...waiting 14.0 seconds
Finished scraping data for the 2019-20 Regular%20Season.
...waiting 8.0 seconds
Finished scraping data for the 2019-20 Playoffs.
...waiting 11.8 seconds
Finished scraping data for the 2020-21 Regular%20Season.
...waiting 13.9 seconds
Finished scraping data for the 2020-21 Playoffs.
...waiting 13.5 seconds
Finished scraping data for the 2021-22 Regular%20Season.
...waiting 38.4 seconds
Finished scraping data for the 2021-22 Playoffs.
...waiting 18.3 seconds
Finished scraping data for the 2022-23 Regular%20Season.
...waiting 27.4 seconds
Finished scraping data for the 2022-23 Playoffs.
...waiting 16.7 seconds
Process completed! Total run time: 7.78

In [72]:
df

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2012-13,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,2012-13,Regular%20Season,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2012-13,Regular%20Season,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,2012-13,Regular%20Season,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2012-13,Regular%20Season,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,2022-23,Regular%20Season,1629126,505,Deonte Burton,1610612758,SAC,2,7,0,2,0.000,0,1,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
507,2022-23,Regular%20Season,1630577,505,Julian Champagnie,1610612759,SAS,2,7,0,2,0.000,0,1,0.000,0,0,0.000,0,0,0,0,1,0,0,0,0,-1,0.00,0.00
508,2022-23,Regular%20Season,1630250,505,Marko Simonovic,1610612741,CHI,3,5,0,1,0.000,0,1,0.000,0,0,0.000,0,0,0,0,0,0,0,1,0,-1,0.00,0.00
509,2022-23,Regular%20Season,1630701,505,Michael Foster Jr.,1610612755,PHI,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
510,2022-23,Regular%20Season,1628425,505,Sterling Brown,1610612747,LAL,4,24,0,4,0.000,0,2,0.000,0,0,0.000,3,5,8,2,3,0,0,4,0,9,0.00,0.00

In [57]:
# file location >> C:\Users\User